name: Tests

on:
  push:
  pull_request:

jobs:
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            testbench: '^8.0'
          - php: '8.2'
            testbench: '^9.0'
          - php: '8.3'
            testbench: '^9.0'
          - php: '8.2'
            testbench: '^10.0'
          - php: '8.3'
            testbench: '^10.0'
          - php: '8.4'
            testbench: '^10.0'
          - php: '8.3'
            testbench: '^11.0'
          - php: '8.4'
            testbench: '^11.0'
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer require --dev orchestra/testbench:${{ matrix.testbench }} --no-update
      - run: composer update --prefer-dist --no-interaction
      - run: vendor/bin/pint --test
      - run: composer test
      - run: composer validate --strict
